version: '3.9'

services:

    postgres:
        image: postgres:12
        hostname: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    scheduler:
        build:
            context: ../
            dockerfile: ./airflow-stack/Dockerfile
            args:
                - AIRFLOW_VERSION=${AIRFLOW_VERSION}
        image: airflow-stack:${AIRFLOW_VERSION}
        command: scheduler -D
        restart: always
        hostname: scheduler
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-scheduler.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    webserver:
        image: airflow-stack:${AIRFLOW_VERSION}
        entrypoint: ./scripts/webserver-entrypoint.sh
        restart: always
        hostname: webserver
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        ports:
            - "8282:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3